# Generated by Django 5.2.7 on 2026-01-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busID', models.CharField(max_length=15)),
                ('busName', models.CharField(max_length=50)),
                ('busTel', models.CharField(max_length=20)),
                ('busEmail', models.CharField(max_length=50)),
                ('busOwner', models.CharField(max_length=50)),
                ('registrationNumber', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessTitle', models.CharField(max_length=50)),
                ('accessDescription', models.CharField(max_length=50)),
                ('accessCode', models.CharField(max_length=6)),
                ('accessGroupCode', models.CharField(max_length=2)),
                ('thisAccessIsPayable', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CodeBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momoNumber', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=4)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchID', models.CharField(max_length=15)),
                ('branchName', models.CharField(max_length=50)),
                ('branchTel', models.CharField(max_length=20)),
                ('branchEmail', models.CharField(max_length=50)),
                ('branchType', models.CharField(max_length=15)),
                ('operateAllTime', models.BooleanField(default=True)),
                ('fromTime', models.TimeField(null=True)),
                ('toTime', models.TimeField(null=True)),
                ('onlineVisibility', models.BooleanField(default=False)),
                ('branchAddress', models.CharField(max_length=100, null=True)),
                ('busRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business')),
            ],
        ),
    ]
