# Generated by Django 5.2.7 on 2026-03-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignPrinterToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busID', models.CharField(max_length=50)),
                ('busName', models.CharField(max_length=100)),
                ('busTel', models.CharField(max_length=50)),
                ('busEmail', models.CharField(max_length=100)),
                ('busOwner', models.CharField(max_length=100)),
                ('registrationNumber', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessTitle', models.CharField(max_length=100)),
                ('accessDescription', models.CharField(max_length=200)),
                ('accessCode', models.CharField(max_length=30)),
                ('accessGroupCode', models.CharField(max_length=10)),
                ('thisAccessIsPayable', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchID', models.CharField(max_length=50)),
                ('branchName', models.CharField(max_length=100)),
                ('branchTel', models.CharField(max_length=50)),
                ('branchEmail', models.CharField(max_length=100)),
                ('branchType', models.CharField(max_length=50)),
                ('operateAllTime', models.BooleanField(default=True)),
                ('fromTime', models.TimeField(null=True)),
                ('toTime', models.TimeField(null=True)),
                ('onlineVisibility', models.BooleanField(default=False)),
                ('branchAddress', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momoNumber', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printerType', models.CharField(max_length=100)),
                ('id1', models.CharField(max_length=100, null=True)),
                ('id2', models.CharField(max_length=100, null=True)),
                ('printerLabel', models.CharField(max_length=100)),
            ],
        ),
    ]
