# Generated by Django 5.2.7 on 2026-01-30 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0001_initial'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.CharField(max_length=100)),
                ('id2', models.CharField(max_length=30)),
                ('printerLabel', models.CharField(max_length=30)),
                ('branchRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
            ],
        ),
        migrations.CreateModel(
            name='AssignPrinterToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.userref')),
                ('printerRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.printers')),
            ],
        ),
    ]
