# Generated by Django 5.2.7 on 2026-03-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0001_initial'),
        ('imageApp', '0001_initial'),
        ('richnet360', '0001_initial'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignprintertouser',
            name='userRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='business',
            name='billRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='richnet360.bill'),
        ),
        migrations.AddField(
            model_name='business',
            name='busLogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imageApp.images'),
        ),
        migrations.AddField(
            model_name='businessbranch',
            name='busRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business'),
        ),
        migrations.AddField(
            model_name='printers',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='assignprintertouser',
            name='printerRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.printers'),
        ),
    ]
