# Generated by Django 5.2.7 on 2026-01-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0002_printers_assignprintertouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers',
            name='id1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='printers',
            name='id2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
