# Generated by Django 5.2.7 on 2026-02-01 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0003_alter_printers_id1_alter_printers_id2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignprintertouser',
            old_name='userID',
            new_name='userRef',
        ),
    ]
