# Generated by Django 5.2.7 on 2026-02-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0004_rename_userid_assignprintertouser_userref'),
    ]

    operations = [
        migrations.AddField(
            model_name='printers',
            name='printerType',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
