# Generated by Django 5.2.7 on 2026-02-04 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0005_printers_printertype'),
        ('richnet360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='billRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='richnet360.bill'),
        ),
    ]
