# Generated by Django 5.2.7 on 2026-02-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0006_business_billref'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(default='Active', max_length=30),
        ),
    ]
