# Generated by Django 5.2.7 on 2026-02-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0007_business_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
