# Generated by Django 5.2.7 on 2026-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0008_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='busEmail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='busID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='busName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='busOwner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='busTel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='businessaccess',
            name='accessCode',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='businessaccess',
            name='accessDescription',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='businessaccess',
            name='accessGroupCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='businessaccess',
            name='accessTitle',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='businessbranch',
            name='branchAddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='businessbranch',
            name='branchEmail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='businessbranch',
            name='branchID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='businessbranch',
            name='branchName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='businessbranch',
            name='branchTel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='businessbranch',
            name='branchType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='codebought',
            name='momoNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='codebought',
            name='pin',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='printers',
            name='id2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='printers',
            name='printerLabel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='printers',
            name='printerType',
            field=models.CharField(max_length=100),
        ),
    ]
