# Generated by Django 5.2.7 on 2026-01-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0001_initial'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BatchOfCrops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchNumber', models.CharField(max_length=50)),
                ('areaPlanted', models.FloatField(default=0.0)),
                ('datePlanted', models.DateField()),
                ('expectedHarvestDate', models.DateField()),
                ('actualHarvestDate', models.DateField(null=True)),
                ('yieldQuantity', models.FloatField(default=0.0)),
                ('yieldAccuracy', models.CharField(default='Estimated', max_length=20)),
                ('cropRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmType', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('farmSize', models.FloatField(default=0.0)),
                ('branchRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
                ('cropRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmApp.crop')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='farmRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.farm'),
        ),
        migrations.CreateModel(
            name='FarmEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentName', models.CharField(max_length=50)),
                ('equipmentType', models.CharField(max_length=50)),
                ('dateAcquired', models.DateField()),
                ('cost', models.FloatField(default=0.0)),
                ('state', models.CharField(default='Good', max_length=20)),
                ('farmRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentMaintenanceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenanceDetails', models.CharField(max_length=300)),
                ('maintenanceDate', models.DateField()),
                ('cost', models.FloatField(default=0.0)),
                ('farmEquipmentRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.farmequipment')),
            ],
        ),
        migrations.CreateModel(
            name='FarmSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonName', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('farmRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='DailyFarmActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityTitle', models.CharField(max_length=100)),
                ('activityDetails', models.CharField(max_length=300)),
                ('activityDateAndTime', models.DateTimeField()),
                ('cost', models.FloatField(default=0.0)),
                ('activityBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref')),
                ('farmRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.farmseason')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordTitle', models.CharField(max_length=100)),
                ('recordDetails', models.CharField(max_length=300)),
                ('dateReported', models.DateField()),
                ('dateTreated', models.DateField(null=True)),
                ('farmRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animalType', models.CharField(max_length=50)),
                ('totalAnimals', models.IntegerField(default=0)),
                ('farmRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.farm')),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='LivestockRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmApp.livestock'),
        ),
        migrations.CreateModel(
            name='BatchOfLivestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchNumber', models.CharField(max_length=50)),
                ('numberOfAnimals', models.IntegerField(default=0)),
                ('dateAdded', models.DateField()),
                ('livestockRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='LivestockByProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(max_length=50)),
                ('qtyType', models.CharField(max_length=20)),
                ('totalProduced', models.FloatField(default=0.0)),
                ('productionDate', models.DateField()),
                ('livestockRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='PerfomedFarmActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePerformed', models.DateField()),
                ('cost', models.FloatField(default=0.0)),
                ('dailyActivityRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmApp.dailyfarmactivities')),
                ('performedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref')),
            ],
        ),
    ]
