# Generated by Django 5.2.7 on 2026-03-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCartBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchCode', models.CharField(max_length=50)),
                ('customerTel', models.CharField(max_length=50)),
                ('status', models.CharField(default='Waiting Payment Request', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=300)),
                ('customerName', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerTel', models.CharField(max_length=50)),
                ('customerName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerTel', models.CharField(max_length=50)),
                ('quantity', models.FloatField(default=0)),
                ('unitPrice', models.FloatField()),
                ('discount', models.FloatField(default=0.0)),
                ('totalPrice', models.FloatField()),
                ('status', models.CharField(default='Waiting Payment Request', max_length=100)),
                ('orderID', models.CharField(max_length=30)),
                ('acceptedCode', models.CharField(default='', max_length=30)),
                ('batchCode', models.CharField(max_length=50)),
                ('paidToAccount', models.CharField(default='', max_length=50)),
                ('date', models.DateTimeField()),
                ('branhRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
            ],
        ),
    ]
