# Generated by Django 5.2.7 on 2026-03-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketPlaceApp', '0001_initial'),
        ('warehouseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddtocart',
            name='productRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.product'),
        ),
    ]
