# Generated by Django 5.2.7 on 2026-03-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketPlaceApp', '0002_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddtocart',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
