# Generated by Django 5.2.7 on 2026-03-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketPlaceApp', '0003_customeraddtocart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=300)),
                ('customerName', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=15)),
            ],
        ),
    ]
