# Generated by Django 5.2.7 on 2026-03-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketPlaceApp', '0004_customerinfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddtocart',
            name='status',
            field=models.CharField(default='Waiting Payment Request', max_length=20),
        ),
    ]
