# Generated by Django 5.2.7 on 2026-03-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketPlaceApp', '0005_alter_customeraddtocart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddtocart',
            name='acceptedCode',
            field=models.CharField(default='', max_length=4),
        ),
    ]
