# Generated by Django 5.2.7 on 2026-03-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketPlaceApp', '0006_customeraddtocart_acceptedcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddtocart',
            name='batchCode',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
