# Generated by Django 5.2.7 on 2026-03-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketPlaceApp', '0007_customeraddtocart_batchcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCartBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchCode', models.CharField(max_length=20)),
                ('customerTel', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='customeraddtocart',
            name='batchCode',
            field=models.CharField(max_length=20),
        ),
    ]
