# Generated by Django 5.2.7 on 2026-03-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketPlaceApp', '0008_currentcartbatch_alter_customeraddtocart_batchcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcartbatch',
            name='status',
            field=models.CharField(default='Waiting Payment Request', max_length=20),
        ),
    ]
