# Generated by Django 5.2.7 on 2026-03-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketPlaceApp', '0009_currentcartbatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddtocart',
            name='acceptedCode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
