# Generated by Django 5.2.7 on 2026-03-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketPlaceApp', '0010_alter_customeraddtocart_acceptedcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddtocart',
            name='paidToAccount',
            field=models.CharField(default='', max_length=30),
        ),
    ]
