# Generated by Django 5.2.7 on 2026-03-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketPlaceApp', '0011_customeraddtocart_paidtoaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddtocart',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
    ]
