# Generated by Django 5.2.7 on 2026-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketPlaceApp', '0012_customeraddtocart_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentcartbatch',
            name='batchCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='currentcartbatch',
            name='customerTel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='currentcartbatch',
            name='status',
            field=models.CharField(default='Waiting Payment Request', max_length=50),
        ),
        migrations.AlterField(
            model_name='customeraddtocart',
            name='acceptedCode',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='customeraddtocart',
            name='batchCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customeraddtocart',
            name='customerTel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customeraddtocart',
            name='orderID',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customeraddtocart',
            name='paidToAccount',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customeraddtocart',
            name='status',
            field=models.CharField(default='Waiting Payment Request', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerinfor',
            name='customerName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerinfor',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerinfor',
            name='tel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='customerName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='customerTel',
            field=models.CharField(max_length=50),
        ),
    ]
