# Generated by Django 5.2.7 on 2026-03-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountType', models.CharField(max_length=50)),
                ('accountName', models.CharField(max_length=100)),
                ('accountNumber', models.CharField(max_length=20, unique=True)),
                ('accountBalance', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.CharField(max_length=30)),
                ('transactionID', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('narration', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetType', models.CharField(max_length=50)),
                ('assetInOut', models.CharField(max_length=10)),
                ('assetName', models.CharField(max_length=100)),
                ('assetValue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dateAcquired', models.DateField()),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashDenominations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash200', models.IntegerField(default=0)),
                ('cash100', models.IntegerField(default=0)),
                ('cash50', models.IntegerField(default=0)),
                ('cash20', models.IntegerField(default=0)),
                ('cash10', models.IntegerField(default=0)),
                ('cash5', models.IntegerField(default=0)),
                ('cash2', models.IntegerField(default=0)),
                ('cash1', models.IntegerField(default=0)),
                ('coins50pesewas', models.IntegerField(default=0)),
                ('coins20pesewas', models.IntegerField(default=0)),
                ('coins10pesewas', models.IntegerField(default=0)),
                ('coins5pesewas', models.IntegerField(default=0)),
                ('coins1pesewa', models.IntegerField(default=0)),
                ('totalCash', models.FloatField(default=0.0)),
                ('cash200Total', models.FloatField(default=0.0)),
                ('cash100Total', models.FloatField(default=0.0)),
                ('cash50Total', models.FloatField(default=0.0)),
                ('cash20Total', models.FloatField(default=0.0)),
                ('cash10Total', models.FloatField(default=0.0)),
                ('cash5Total', models.FloatField(default=0.0)),
                ('cash2Total', models.FloatField(default=0.0)),
                ('cash1Total', models.FloatField(default=0.0)),
                ('coins50pesewasTotal', models.FloatField(default=0.0)),
                ('coins20pesewasTotal', models.FloatField(default=0.0)),
                ('coins10pesewasTotal', models.FloatField(default=0.0)),
                ('coins5pesewasTotal', models.FloatField(default=0.0)),
                ('coins1pesewaTotal', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Fund not transfered', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyProfitLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('totalRevenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalExpenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('netProfit', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equityType', models.CharField(max_length=50)),
                ('equityInOut', models.CharField(max_length=10)),
                ('equityName', models.CharField(max_length=100)),
                ('equityAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dateRecorded', models.DateField()),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liabilityType', models.CharField(max_length=50)),
                ('liabilityInOut', models.CharField(max_length=10)),
                ('liabilityName', models.CharField(max_length=100)),
                ('liabilityAmount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dateIncurred', models.DateField()),
                ('description', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=50)),
                ('accountName', models.CharField(max_length=50)),
                ('accountType', models.CharField(default='Mobile Money Account', max_length=50)),
                ('subscriber', models.CharField(default='', max_length=100)),
                ('bankName', models.CharField(default='', max_length=100)),
                ('bankBranchName', models.CharField(default='', max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OperationExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseType', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dateIncurred', models.DateField()),
                ('description', models.CharField(max_length=255, null=True)),
                ('transactionIsConfirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OversAndShortages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overAmount', models.FloatField(default=0.0)),
                ('shortageAmount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='OversAndShortagesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OverWithdrawalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawalType', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('narration', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PayRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('staffID', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('ssnit', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=50)),
                ('wageType', models.CharField(max_length=20)),
                ('currentSalary', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ShortagePaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('narration', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SuspenseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(default='cashOnHand', max_length=50)),
                ('transactionID', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('oversAmount', models.FloatField(default=0.0)),
                ('shortageAmount', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TransferFundsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferType', models.CharField(max_length=50)),
                ('transactionID', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('narration', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('transerStatus', models.CharField(max_length=50)),
            ],
        ),
    ]
