# Generated by Django 5.2.7 on 2026-03-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountsApp', '0001_initial'),
        ('businessApp', '0002_initial'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaccess',
            name='branchRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='accountaccess',
            name='enteredBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='branchRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='busRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business'),
        ),
        migrations.AddField(
            model_name='accountaccess',
            name='accountRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountsApp.accounts'),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='accountRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountsApp.accounts'),
        ),
        migrations.AddField(
            model_name='accounttransaction',
            name='enteredBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='asset',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='asset',
            name='busRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business'),
        ),
        migrations.AddField(
            model_name='asset',
            name='enteredBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
    ]
