# Generated by Django 5.2.7 on 2026-01-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0002_initial'),
        ('businessApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('staffID', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('ssnit', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=50)),
                ('wageType', models.CharField(max_length=20)),
                ('currentSalary', models.FloatField(default=0.0)),
                ('busRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business')),
            ],
        ),
    ]
