# Generated by Django 5.2.7 on 2026-03-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountsApp', '0002_initial'),
        ('businessApp', '0002_initial'),
        ('salesApp', '0001_initial'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdenominations',
            name='CashOnhandRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salesApp.cashonhand'),
        ),
        migrations.AddField(
            model_name='cashdenominations',
            name='addedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='cashdenominations',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='cashdenominations',
            name='busRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business'),
        ),
        migrations.AddField(
            model_name='dailyprofitloss',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='dailyprofitloss',
            name='busRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business'),
        ),
        migrations.AddField(
            model_name='equity',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='equity',
            name='busRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business'),
        ),
        migrations.AddField(
            model_name='equity',
            name='enteredBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='liability',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='liability',
            name='busRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business'),
        ),
        migrations.AddField(
            model_name='liability',
            name='enteredBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='onlineaccounts',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='operationexpenses',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='operationexpenses',
            name='busRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business'),
        ),
        migrations.AddField(
            model_name='operationexpenses',
            name='enteredBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='oversandshortages',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='oversandshortages',
            name='busRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business'),
        ),
        migrations.AddField(
            model_name='oversandshortages',
            name='fromAccountRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountsApp.accounts'),
        ),
        migrations.AddField(
            model_name='oversandshortagesrecord',
            name='oversAndShortagesRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountsApp.oversandshortages'),
        ),
        migrations.AddField(
            model_name='overwithdrawalrecord',
            name='accountRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountsApp.accounts'),
        ),
        migrations.AddField(
            model_name='overwithdrawalrecord',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='overwithdrawalrecord',
            name='busRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business'),
        ),
        migrations.AddField(
            model_name='overwithdrawalrecord',
            name='enteredBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='overwithdrawalrecord',
            name='oversAndShortagesRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountsApp.oversandshortages'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='busRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business'),
        ),
        migrations.AddField(
            model_name='shortagepaymentrecord',
            name='enteredBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='shortagepaymentrecord',
            name='oversAndShortagesRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountsApp.oversandshortages'),
        ),
        migrations.AddField(
            model_name='suspenseaccount',
            name='busRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business'),
        ),
        migrations.AddField(
            model_name='suspenseaccount',
            name='enteredBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='suspenseaccount',
            name='fromAccountRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspense_from_account', to='accountsApp.accounts'),
        ),
        migrations.AddField(
            model_name='suspenseaccount',
            name='fromBranch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_branch', to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='suspenseaccount',
            name='toAccountRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspense_to_account', to='accountsApp.accounts'),
        ),
        migrations.AddField(
            model_name='suspenseaccount',
            name='toBranch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_branch', to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='transferfundsrecord',
            name='confirmBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='confirm_by', to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='transferfundsrecord',
            name='enteredBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entered_by', to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='transferfundsrecord',
            name='fromAccountRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='accountsApp.accounts'),
        ),
        migrations.AddField(
            model_name='transferfundsrecord',
            name='toAccountRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='accountsApp.accounts'),
        ),
    ]
