# Generated by Django 5.2.7 on 2026-03-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0003_payroll'),
        ('businessApp', '0008_business_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=30)),
                ('accountName', models.CharField(max_length=50)),
                ('accountType', models.CharField(default='Mobile Money Account', max_length=15)),
                ('subscriber', models.CharField(default='', max_length=30)),
                ('bankName', models.CharField(default='', max_length=30)),
                ('bankBranchName', models.CharField(default='', max_length=30)),
                ('date', models.DateField()),
                ('branchRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
            ],
        ),
    ]
