# Generated by Django 5.2.7 on 2026-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsApp', '0004_onlineaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='accountName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='accountType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='transactionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='transactionType',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cashdenominations',
            name='status',
            field=models.CharField(default='Fund not transfered', max_length=50),
        ),
        migrations.AlterField(
            model_name='onlineaccounts',
            name='accountNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='onlineaccounts',
            name='accountType',
            field=models.CharField(default='Mobile Money Account', max_length=50),
        ),
        migrations.AlterField(
            model_name='onlineaccounts',
            name='bankBranchName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='onlineaccounts',
            name='bankName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='onlineaccounts',
            name='subscriber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='oversandshortagesrecord',
            name='transactionType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='overwithdrawalrecord',
            name='withdrawalType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shortagepaymentrecord',
            name='paymentType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='suspenseaccount',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='suspenseaccount',
            name='option',
            field=models.CharField(default='cashOnHand', max_length=50),
        ),
        migrations.AlterField(
            model_name='suspenseaccount',
            name='transactionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transferfundsrecord',
            name='transactionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transferfundsrecord',
            name='transerStatus',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transferfundsrecord',
            name='transferType',
            field=models.CharField(max_length=50),
        ),
    ]
