# Generated by Django 5.2.7 on 2026-01-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.CharField(max_length=10)),
                ('roomType', models.CharField(max_length=30)),
                ('bedType', models.CharField(max_length=30)),
                ('pricePerHour', models.FloatField(default=0.0)),
                ('isAvailable', models.BooleanField(default=True)),
                ('branchRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
            ],
        ),
        migrations.CreateModel(
            name='HotelBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingNumber', models.CharField(max_length=20)),
                ('guestName', models.CharField(max_length=50)),
                ('guestTel', models.CharField(max_length=20)),
                ('checkInDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('totalAmount', models.FloatField(default=0.0)),
                ('bookingStatus', models.CharField(default='Booked', max_length=20)),
                ('hotelRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelApp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='BookingIncidentReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportTitle', models.CharField(max_length=100)),
                ('reportDetails', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('hotelBookingRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelApp.hotelbookings')),
            ],
        ),
        migrations.CreateModel(
            name='HotelServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=50)),
                ('serviceDescription', models.CharField(max_length=200, null=True)),
                ('servicePrice', models.FloatField(default=0.0)),
                ('hotelRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelApp.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='GuestServicesUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestName', models.CharField(max_length=50)),
                ('guestTel', models.CharField(max_length=20)),
                ('usageDate', models.DateField()),
                ('usageTime', models.TimeField()),
                ('amountCharged', models.FloatField(default=0.0)),
                ('hotelServiceRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelApp.hotelservices')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenityName', models.CharField(max_length=50)),
                ('amenityDescription', models.CharField(max_length=200, null=True)),
                ('hotelRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelApp.hotel')),
            ],
        ),
    ]
