# Generated by Django 5.2.7 on 2026-01-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0001_initial'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryGuys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleType', models.CharField(max_length=30)),
                ('vehicleNumber', models.CharField(max_length=20)),
                ('userRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.userref')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantAndBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCode', models.CharField(max_length=50)),
                ('itemType', models.CharField(max_length=50)),
                ('itemPrice', models.FloatField(default=0.0)),
                ('isAvailable', models.BooleanField(default=True)),
                ('branchRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReportsRestaurantAndBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportTitle', models.CharField(max_length=100)),
                ('reportDetails', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('restaurantRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantAndBarApp.restaurantandbar')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.CharField(max_length=20)),
                ('customerName', models.CharField(max_length=50)),
                ('customerTel', models.CharField(max_length=20)),
                ('totalPrice', models.FloatField(default=0.0)),
                ('orderStatus', models.CharField(default='Pending', max_length=20)),
                ('orderType', models.CharField(default='Dine-in', max_length=20)),
                ('orderDate', models.DateField()),
                ('modeOfPayment', models.CharField(default='Cash', max_length=20)),
                ('deliveryGuyRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantAndBarApp.deliveryguys')),
                ('restaurantRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantAndBarApp.restaurantandbar')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('totalPrice', models.FloatField(default=0.0)),
                ('orderRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantAndBarApp.customerorders')),
                ('itemRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantAndBarApp.restaurantandbar')),
            ],
        ),
    ]
