# Generated by Django 5.2.7 on 2026-03-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logDetails', models.CharField(max_length=200)),
                ('logTitle', models.CharField(default='New activity log', max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('homeTown', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessaccess')),
            ],
        ),
        migrations.CreateModel(
            name='UserRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userIsAdmin', models.BooleanField(default=False)),
                ('userID', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=260)),
                ('status', models.CharField(default='Offline', max_length=50)),
                ('passwordIsSet', models.BooleanField(default=False)),
                ('accessRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.useraccess')),
                ('busRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
                ('logRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userlogs')),
                ('userRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.users')),
            ],
        ),
        migrations.AddField(
            model_name='userlogs',
            name='userRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='userRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.userref'),
        ),
    ]
