# Generated by Django 5.2.7 on 2026-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs',
            name='logTitle',
            field=models.CharField(default='New activity log', max_length=100),
        ),
        migrations.AlterField(
            model_name='userref',
            name='status',
            field=models.CharField(default='Offline', max_length=50),
        ),
        migrations.AlterField(
            model_name='userref',
            name='userID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='homeTown',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='tel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
