# Generated by Django 5.2.7 on 2026-01-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerName', models.CharField(max_length=50, null=True)),
                ('passengerTel', models.CharField(max_length=20)),
                ('seatNumber', models.CharField(max_length=10)),
                ('ticketNumber', models.CharField(max_length=20)),
                ('fare', models.FloatField(default=0.0)),
                ('status', models.CharField(default='In Transit', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PassengerGoodsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsDescription', models.CharField(max_length=200)),
                ('weight', models.FloatField(default=0.0)),
                ('fare', models.FloatField(default=0.0)),
                ('passengerRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportationApp.passengerdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleNumber', models.CharField(max_length=20)),
                ('vehicleType', models.CharField(max_length=30)),
                ('capacity', models.FloatField(default=0.0)),
                ('driverName', models.CharField(max_length=50)),
                ('driverTel', models.CharField(max_length=20)),
                ('branchRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderName', models.CharField(max_length=50)),
                ('senderTel', models.CharField(max_length=20)),
                ('receiverName', models.CharField(max_length=50)),
                ('receiverTel', models.CharField(max_length=20)),
                ('parcelDescription', models.CharField(max_length=200)),
                ('weight', models.FloatField(default=0.0)),
                ('status', models.CharField(default='In Transit', max_length=20)),
                ('transportationRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportationApp.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='TransportationIncidentReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportTitle', models.CharField(max_length=100)),
                ('reportDetails', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('transportationRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportationApp.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='TransportationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleType', models.CharField(max_length=30)),
                ('transportationType', models.CharField(max_length=30)),
                ('departureLocation', models.CharField(max_length=100)),
                ('arrivalLocation', models.CharField(max_length=100)),
                ('departureDate', models.DateField()),
                ('arrivalDate', models.DateField()),
                ('distance', models.FloatField(default=0.0)),
                ('fare', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Scheduled', max_length=20)),
                ('transportationRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportationApp.transportation')),
            ],
        ),
        migrations.AddField(
            model_name='transportation',
            name='scheduleRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transportationApp.transportationschedule'),
        ),
        migrations.AddField(
            model_name='passengerdetails',
            name='transportationRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportationApp.transportationschedule'),
        ),
    ]
