# Generated by Django 5.2.7 on 2026-01-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventType', models.CharField(max_length=50)),
                ('eventLocation', models.CharField(max_length=100)),
                ('organizerName', models.CharField(max_length=50)),
                ('organizerTel', models.CharField(max_length=20)),
                ('totalTickets', models.IntegerField(default=0)),
                ('totalSeat', models.IntegerField(default=0)),
                ('numberOfSession', models.IntegerField(default=1)),
                ('ticketsSold', models.IntegerField(default=0)),
                ('ticketsAvailable', models.IntegerField(default=0)),
                ('branchRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
            ],
        ),
        migrations.CreateModel(
            name='EventSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleTitle', models.CharField(max_length=100)),
                ('scheduleDetails', models.CharField(max_length=300)),
                ('scheduleDate', models.DateField()),
                ('scheduleTime', models.TimeField()),
                ('eventRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventManagementApp.eventmanagement')),
            ],
        ),
        migrations.CreateModel(
            name='SeatNumbering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatNumber', models.CharField(max_length=10)),
                ('eventRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventManagementApp.eventmanagement')),
            ],
        ),
        migrations.CreateModel(
            name='TicketCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('categoryDescription', models.CharField(max_length=200, null=True)),
                ('ticketPrice', models.FloatField(default=0.0)),
                ('totalTickets', models.IntegerField(default=0)),
                ('ticketsSold', models.IntegerField(default=0)),
                ('ticketsAvailable', models.IntegerField(default=0)),
                ('eventRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventManagementApp.eventmanagement')),
            ],
        ),
        migrations.CreateModel(
            name='EmbossedTicketDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketID', models.CharField(max_length=50)),
                ('embossingDetails', models.CharField(max_length=200)),
                ('qrCodeData', models.CharField(max_length=200, null=True)),
                ('isSold', models.BooleanField(default=False)),
                ('ticketCategoryRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventManagementApp.ticketcategories')),
            ],
        ),
        migrations.CreateModel(
            name='TicketsPurchaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketNumber', models.CharField(max_length=20)),
                ('purchaserName', models.CharField(max_length=50)),
                ('purchaserTel', models.CharField(max_length=20)),
                ('purchaseDate', models.DateField()),
                ('seatNumber', models.CharField(max_length=10, null=True)),
                ('ticketStatus', models.CharField(default='Valid', max_length=20)),
                ('ticketsRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventManagementApp.embossedticketdetails')),
            ],
        ),
        migrations.AddField(
            model_name='embossedticketdetails',
            name='purchaserRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eventManagementApp.ticketspurchaser'),
        ),
    ]
