# Generated by Django 5.2.7 on 2026-01-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyType', models.CharField(max_length=50)),
                ('size', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=500, null=True)),
                ('availabilityStatus', models.CharField(default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estateType', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('ownerName', models.CharField(max_length=50)),
                ('ownerTel', models.CharField(max_length=20)),
                ('branchRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
                ('esateDetailRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realEstateApp.estatedetails')),
            ],
        ),
        migrations.CreateModel(
            name='EstateViewings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewerName', models.CharField(max_length=50)),
                ('viewerTel', models.CharField(max_length=20)),
                ('viewingDate', models.DateField()),
                ('viewingTime', models.TimeField()),
                ('realEstateRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstateApp.realestate')),
            ],
        ),
        migrations.CreateModel(
            name='EstateSalesRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerName', models.CharField(max_length=50)),
                ('buyerTel', models.CharField(max_length=20)),
                ('salePrice', models.FloatField(default=0.0)),
                ('saleDate', models.DateField()),
                ('realEstateRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstateApp.realestate')),
            ],
        ),
        migrations.CreateModel(
            name='EstateRentalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renterName', models.CharField(max_length=50)),
                ('renterTel', models.CharField(max_length=20)),
                ('rentAmount', models.FloatField(default=0.0)),
                ('rentStartDate', models.DateField()),
                ('rentEndDate', models.DateField()),
                ('realEstateRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstateApp.realestate')),
            ],
        ),
        migrations.CreateModel(
            name='EstateMaintenanceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenanceDetails', models.CharField(max_length=300)),
                ('maintenanceDate', models.DateField()),
                ('cost', models.FloatField(default=0.0)),
                ('estateDetailRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstateApp.realestate')),
            ],
        ),
    ]
