# Generated by Django 5.2.7 on 2026-01-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0001_initial'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchOfManufacturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchNumber', models.CharField(max_length=50)),
                ('expectedQuantity', models.FloatField(default=0.0)),
                ('actualQuantityProduced', models.FloatField(default=0.0)),
                ('productionDate', models.DateField()),
                ('expectedCompletionDate', models.DateField()),
                ('actualCompletionDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockAvailable', models.FloatField(default=0.0)),
                ('costPricePerStock', models.FloatField(default=0.0)),
                ('sellingPerStock', models.FloatField(default=0.0)),
                ('restockLevel', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialsUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialName', models.CharField(max_length=100)),
                ('quantityUsed', models.FloatField(default=0.0)),
                ('costPerUnit', models.FloatField(default=0.0)),
                ('totalCost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RequestedRawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialName', models.CharField(max_length=100)),
                ('quantityRequested', models.FloatField(default=0.0)),
                ('requestStatus', models.CharField(default='Pending', max_length=20)),
                ('requestDate', models.DateField()),
                ('respondDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinisedProductsStorageInWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storageLocation', models.CharField(max_length=100)),
                ('quantityStored', models.FloatField(default=0.0)),
                ('dateStored', models.DateField()),
                ('manufacturingRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturingApp.batchofmanufacturedproducts')),
                ('storedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCode', models.CharField(max_length=50)),
                ('ProductDescription', models.CharField(max_length=200, null=True)),
                ('productType', models.CharField(default='Raw Material', max_length=50)),
                ('branchRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
                ('finishedProductRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manufacturingApp.finishedproduct')),
            ],
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='manufacturingRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturingApp.manufacturing'),
        ),
        migrations.CreateModel(
            name='DamageProductsRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(default='Raw Material', max_length=50)),
                ('quantityDamage', models.FloatField(default=0.0)),
                ('costInvolve', models.FloatField(default=0.0)),
                ('manufacturingRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturingApp.manufacturing')),
            ],
        ),
        migrations.AddField(
            model_name='batchofmanufacturedproducts',
            name='manufacturingRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturingApp.manufacturing'),
        ),
        migrations.CreateModel(
            name='ManufacturingIncidentReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportTitle', models.CharField(max_length=100)),
                ('reportDetails', models.CharField(max_length=300)),
                ('costInvolved', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('manufacturingRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturingApp.batchofmanufacturedproducts')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingProcesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processName', models.CharField(max_length=100)),
                ('processDescription', models.CharField(max_length=300, null=True)),
                ('processPercentage', models.FloatField(default=0.0)),
                ('manufacturingRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturingApp.batchofmanufacturedproducts')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationName', models.CharField(max_length=100)),
                ('operationDescription', models.CharField(max_length=300, null=True)),
                ('operationDate', models.DateField()),
                ('cost', models.FloatField(default=0.0)),
                ('manufacturingProcessRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturingApp.manufacturingprocesses')),
                ('operationBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockAvailable', models.FloatField(default=0.0)),
                ('costPerStock', models.FloatField(default=0.0)),
                ('restockLevel', models.FloatField(default=0)),
                ('manufacturingRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturingApp.manufacturing')),
            ],
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='rawMaterialRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manufacturingApp.rawmaterial'),
        ),
    ]
