# Generated by Django 5.2.7 on 2026-03-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturingApp', '0001_initial'),
        ('usersApp', '0001_initial'),
        ('warehouseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialsused',
            name='ProductRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.product'),
        ),
        migrations.AddField(
            model_name='rawmaterialsused',
            name='manufacturingRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturingApp.processoperations'),
        ),
        migrations.AddField(
            model_name='requestedrawmaterials',
            name='ProductRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.product'),
        ),
        migrations.AddField(
            model_name='requestedrawmaterials',
            name='manufacturingRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturingApp.batchofmanufacturedproducts'),
        ),
        migrations.AddField(
            model_name='requestedrawmaterials',
            name='requestedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='requestedrawmaterials',
            name='respondedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responder', to='usersApp.userref'),
        ),
    ]
