# Generated by Django 5.2.7 on 2026-03-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentBill', models.FloatField(default=0.0)),
                ('arrears', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='BillPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busID', models.CharField(max_length=50)),
                ('amountPaid', models.FloatField(default=0.0)),
                ('outstandingBalance', models.FloatField(default=0.0)),
                ('transactionID', models.CharField(max_length=100, null=True)),
                ('paymentType', models.CharField(default='MoMo', max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busID', models.CharField(max_length=50)),
                ('product', models.CharField(default='Monthly Charges', max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ChargesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0.0)),
                ('period', models.CharField(default='Not Set', max_length=50)),
                ('narration', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CheckNextBillDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nextBillDate', models.DateField()),
                ('busRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business')),
                ('chargeRef', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='richnet360.chargestype')),
            ],
        ),
    ]
