# Generated by Django 5.2.7 on 2026-02-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentBill', models.FloatField(default=0.0)),
                ('arrears', models.FloatField(default=0.0)),
                ('nextBillDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BillPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busID', models.CharField(max_length=50)),
                ('amountPaid', models.FloatField(default=0.0)),
                ('outstandingBalance', models.FloatField(default=0.0)),
                ('transactionID', models.CharField(max_length=50, null=True)),
                ('paymentType', models.CharField(default='MoMo', max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busID', models.CharField(max_length=50)),
                ('product', models.CharField(default='Monthly Charges', max_length=30)),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('chargePerProduct', models.FloatField(default=0.0)),
            ],
        ),
    ]
