# Generated by Django 5.2.7 on 2026-02-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richnet360', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='chargePerProduct',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='productName',
            new_name='charge',
        ),
        migrations.AddField(
            model_name='products',
            name='narration',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='period',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
