# Generated by Django 5.2.7 on 2026-02-11 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('richnet360', '0002_rename_chargeperproduct_products_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='charge',
            new_name='product',
        ),
    ]
