# Generated by Django 5.2.7 on 2026-02-11 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('richnet360', '0003_rename_charge_products_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='ChargesType',
        ),
    ]
