# Generated by Django 5.2.7 on 2026-02-13 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0008_business_description'),
        ('richnet360', '0004_rename_products_chargestype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='nextBillDate',
        ),
        migrations.CreateModel(
            name='CheckNextBillDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nextBillDate', models.DateField()),
                ('busRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business')),
                ('chartRef', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='richnet360.chargestype')),
            ],
        ),
    ]
