# Generated by Django 5.2.7 on 2026-02-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richnet360', '0005_remove_bill_nextbilldate_checknextbilldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargestype',
            name='period',
            field=models.CharField(default='Not Set', max_length=30),
        ),
    ]
