# Generated by Django 5.2.7 on 2026-02-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('richnet360', '0006_alter_chargestype_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checknextbilldate',
            old_name='chartRef',
            new_name='chargeRef',
        ),
    ]
