# Generated by Django 5.2.7 on 2026-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richnet360', '0007_rename_chartref_checknextbilldate_chargeref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayments',
            name='paymentType',
            field=models.CharField(default='MoMo', max_length=50),
        ),
        migrations.AlterField(
            model_name='billpayments',
            name='transactionID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='charges',
            name='product',
            field=models.CharField(default='Monthly Charges', max_length=50),
        ),
        migrations.AlterField(
            model_name='chargestype',
            name='period',
            field=models.CharField(default='Not Set', max_length=50),
        ),
        migrations.AlterField(
            model_name='chargestype',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
