# Generated by Django 5.2.7 on 2026-03-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0001_initial'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.CharField(max_length=100, unique=True)),
                ('subjectID', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('extention', models.CharField(max_length=20)),
                ('imgType', models.CharField(default='product', max_length=30)),
                ('date', models.DateTimeField()),
                ('busRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business')),
                ('userRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApp.userref')),
            ],
        ),
        migrations.CreateModel(
            name='OtherFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueID', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('extention', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('imageRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageApp.images')),
            ],
        ),
    ]
