# Generated by Django 5.2.7 on 2026-02-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
