# Generated by Django 5.2.7 on 2026-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0003_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='extention',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='images',
            name='imgType',
            field=models.CharField(default='product', max_length=30),
        ),
        migrations.AlterField(
            model_name='images',
            name='subjectID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='images',
            name='uniqueID',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='otherfiles',
            name='extention',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='otherfiles',
            name='uniqueID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
