# Generated by Django 5.2.7 on 2026-03-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePaymentItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quatity', models.FloatField()),
                ('pricePerUnit', models.FloatField()),
                ('costPerUnit', models.FloatField()),
                ('totalPrice', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AdvancePaymentItemsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationType', models.CharField(default='Collected', max_length=50)),
                ('quantity', models.FloatField()),
                ('balace', models.FloatField()),
                ('date', models.DateTimeField()),
                ('receiverName', models.CharField(max_length=100)),
                ('receiverTel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AgreementConfirmationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('customerContact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AllCustomerTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=100)),
                ('paymentTerms', models.CharField(max_length=100)),
                ('transactionType', models.CharField(default='Purchased', max_length=50)),
                ('transactionDate', models.DateField()),
                ('totalPrice', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('currentPayment', models.FloatField(default=0.0)),
                ('amountTopay', models.FloatField(default=0.0)),
                ('amountPaid', models.FloatField(default=0.0)),
                ('amountOwe', models.FloatField(default=0.0)),
                ('oweBalance', models.FloatField(default=0.0)),
                ('narration', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CashOnhand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.FloatField(default=0.0)),
                ('totalTransaction', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentCostAndPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costPrice', models.FloatField(default=0.0)),
                ('unitCostPrice', models.FloatField(default=0.0)),
                ('sellingPrice', models.FloatField(default=0.0)),
                ('unitSellingPrice', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerItemsPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=100)),
                ('productName', models.CharField(max_length=100)),
                ('productCode', models.CharField(max_length=50)),
                ('measureUnit', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('quantityReturned', models.FloatField(default=0)),
                ('pricePerUnit', models.FloatField(default=0.0)),
                ('costPerUnit', models.FloatField(default=0.0)),
                ('promotionRate', models.FloatField(default=0.0)),
                ('unitDiscount', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('totalPrice', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOwingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=100)),
                ('operationType', models.CharField(max_length=30)),
                ('amount', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=100)),
                ('amountOwe', models.FloatField(default=0.0)),
                ('amountPaid', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('paidBy', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomMeasuringUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('unityType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DatesForPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('penalty', models.FloatField(default=0.0)),
                ('day', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(default=0.0)),
                ('discountSwaper', models.FloatField(default=0.0)),
                ('startFrom', models.DateTimeField(null=True)),
                ('endAt', models.DateTimeField(null=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExcludeDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualItemsSupplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('unityCost', models.FloatField(default=0.0)),
                ('totalCost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='MeasuringUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockedUnit', models.CharField(max_length=100)),
                ('soldUnit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=100)),
                ('paymentTerm', models.CharField(max_length=50)),
                ('numberDays', models.IntegerField()),
                ('daysBeforeNextPayment', models.IntegerField()),
                ('agreementLetter', models.CharField(max_length=500)),
                ('nextPaymentDate', models.DateField()),
                ('nextPaymentAmount', models.FloatField(default=0.0)),
                ('totalAmount', models.FloatField(default=0.0)),
                ('paneltyRatePerBreach', models.FloatField(default=0.0)),
                ('totalPaneltyCharges', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAgreementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateToPay', models.DateField()),
                ('paidOn', models.DateField()),
                ('panelty', models.FloatField()),
                ('amountPaid', models.FloatField(default=0.0)),
                ('amountRemain', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prices', models.FloatField(default=0.0)),
                ('costs', models.FloatField(default=0.0)),
                ('changeDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierName', models.CharField(max_length=100)),
                ('supplierContact', models.CharField(max_length=100)),
                ('supplierAddress', models.CharField(max_length=200)),
                ('amountOwed', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Quantities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtyPerPack', models.FloatField(default=1.0)),
                ('packQty', models.FloatField(default=0.0)),
                ('uintQty', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RetailAndWholesale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityInStock', models.FloatField(default=0.0)),
                ('reorderLevel', models.FloatField(default=0.0)),
                ('partCanBeSold', models.BooleanField(default=True)),
                ('isVisibleOnline', models.BooleanField(default=True)),
                ('enableOnlineOrder', models.BooleanField(default=False)),
                ('minimumOrder', models.FloatField(default=1)),
                ('returnPeriod', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RetailAndWholesaleCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('customerContact', models.CharField(max_length=100)),
                ('customerAddress', models.CharField(max_length=200, null=True)),
                ('totalAmountOwed', models.FloatField(default=0.0)),
                ('lastTransactionDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetailAndWholesaleIncidentReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportTitle', models.CharField(max_length=100)),
                ('reportDetails', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RetailWholesalesTally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.CharField(default='In', max_length=20)),
                ('quantity', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('unitQuantity', models.FloatField(default=0.0)),
                ('uintBalance', models.FloatField(default=0.0)),
                ('narration', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReturnAmountToCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountToPay', models.FloatField(default=0.0)),
                ('status', models.CharField(default='Pending', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnedProductsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('pricePerUnit', models.FloatField(default=0.0)),
                ('totalPrice', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=100)),
                ('paymentTerms', models.CharField(max_length=50, null=True)),
                ('customerName', models.CharField(max_length=100, null=True)),
                ('customerTel', models.CharField(max_length=50, null=True)),
                ('totalAmount', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('amountToPay', models.FloatField(default=0.0)),
                ('amountPaid', models.FloatField(default=0.0)),
                ('amountOwe', models.FloatField(default=0.0)),
                ('amountReturned', models.FloatField(default=0.0)),
                ('transactionDate', models.DateField()),
                ('transactionIsConfirm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustmentType', models.CharField(default='Wrong Entry', max_length=50)),
                ('transactionType', models.CharField(default='Out', max_length=20)),
                ('quantity', models.FloatField(default=0.0)),
                ('oldStock', models.FloatField(default=0.0)),
                ('newStock', models.FloatField(default=0.0)),
                ('oldStockUnit', models.FloatField(default=0.0)),
                ('newStockUnit', models.FloatField(default=0.0)),
                ('narration', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SupplyQuantityRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=100, null=True)),
                ('transactionType', models.CharField(default='Supply', max_length=50)),
                ('receiptNumber', models.CharField(max_length=50, null=True)),
                ('totalCost', models.FloatField(default=0.0)),
                ('amountPaid', models.FloatField(default=0.0)),
                ('amountOwe', models.FloatField(default=0.0)),
                ('Balance', models.FloatField(default=0.0)),
                ('supplyDate', models.DateField()),
                ('narration', models.CharField(default='', max_length=500)),
                ('isDisabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TemporalPurchaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=100)),
                ('totalPrice', models.FloatField(default=0.0)),
                ('amountToPay', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('discountRate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TempSupplyQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('amountPaid', models.FloatField(default=0.0)),
                ('amountOwe', models.FloatField(default=0.0)),
                ('unityCost', models.FloatField(default=0.0)),
                ('totalCost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionIDs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=100, unique=True)),
                ('isSelcted', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=100)),
                ('quantity', models.FloatField(default=0.0)),
                ('pricePerItem', models.FloatField(default=0.0)),
                ('totalPrice', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('branchRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
            ],
        ),
    ]
