# Generated by Django 5.2.7 on 2026-01-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0001_initial'),
        ('salesApp', '0001_initial'),
        ('usersApp', '0001_initial'),
        ('warehouseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='productRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.product'),
        ),
        migrations.AddField(
            model_name='addtocart',
            name='transactionBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='advancepaymentitems',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='advancepaymentitems',
            name='productRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.product'),
        ),
        migrations.AddField(
            model_name='advancepaymentitemsdetails',
            name='advanceItemRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.advancepaymentitems'),
        ),
        migrations.AddField(
            model_name='agreementconfirmationcode',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='cashonhand',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='cashonhand',
            name='userRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='customeritemspurchased',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='customerpayments',
            name='paymentBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='custommeasuringunit',
            name='branchRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='custommeasuringunit',
            name='bussRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business'),
        ),
        migrations.AddField(
            model_name='discountrate',
            name='addedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='individualDiscount', to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='discountrate',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='discountrate',
            name='productRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.product'),
        ),
        migrations.AddField(
            model_name='paymentagreement',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='datesforpayments',
            name='payAgreemtRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.paymentagreement'),
        ),
        migrations.AddField(
            model_name='advancepaymentitems',
            name='payAgreemtRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.paymentagreement'),
        ),
        migrations.AddField(
            model_name='paymentagreementdetails',
            name='payAgreemtRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.paymentagreement'),
        ),
        migrations.AddField(
            model_name='productsuppliers',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='retailandwholesale',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='retailandwholesale',
            name='currentCostPriceRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salesApp.currentcostandprice'),
        ),
        migrations.AddField(
            model_name='retailandwholesale',
            name='discountRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salesApp.discountrate'),
        ),
        migrations.AddField(
            model_name='retailandwholesale',
            name='measureRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salesApp.measuringunits'),
        ),
        migrations.AddField(
            model_name='retailandwholesale',
            name='quantityRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salesApp.quantities'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='retailAndWholesaleRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.retailandwholesale'),
        ),
        migrations.AddField(
            model_name='retailandwholesalecustomers',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='customerowingdetails',
            name='customerRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.retailandwholesalecustomers'),
        ),
        migrations.AddField(
            model_name='retailandwholesaleincidentreports',
            name='retailAndWholesaleRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.retailandwholesale'),
        ),
        migrations.AddField(
            model_name='retailwholesalestally',
            name='retailAndWholesaleRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.retailandwholesale'),
        ),
        migrations.AddField(
            model_name='retailwholesalestally',
            name='transactionBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='salesrecords',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='salesrecords',
            name='customerRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salesApp.retailandwholesalecustomers'),
        ),
        migrations.AddField(
            model_name='salesrecords',
            name='transactionBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='customerpayments',
            name='salesRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.salesrecords'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='retailAndWholesaleRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.retailandwholesale'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='transactionBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
        migrations.AddField(
            model_name='supplyquantityrecords',
            name='retailAndWholesaleRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.retailandwholesale'),
        ),
        migrations.AddField(
            model_name='supplyquantityrecords',
            name='supplierRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.productsuppliers'),
        ),
        migrations.AddField(
            model_name='temporalpurchasedetails',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='transactionids',
            name='branchRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
        migrations.AddField(
            model_name='transactionids',
            name='userRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
        ),
    ]
