# Generated by Django 5.2.7 on 2026-01-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecords',
            name='customerOwingBalance',
            field=models.FloatField(default=0.0),
        ),
    ]
