# Generated by Django 5.2.7 on 2026-03-29 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempsupplyquantity',
            name='supplierRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salesApp.productsuppliers'),
        ),
    ]
