# Generated by Django 5.2.7 on 2026-01-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0003_salesrecords_customerowingbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecords',
            name='transactionType',
            field=models.CharField(default='Purchased', max_length=15),
        ),
    ]
