# Generated by Django 5.2.7 on 2026-04-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0003_alter_tempsupplyquantity_supplierref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailandwholesale',
            name='isVisibleOnline',
            field=models.BooleanField(default=False),
        ),
    ]
