# Generated by Django 5.2.7 on 2026-01-06 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0004_salesrecords_transactiontype'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCustomerTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionID', models.CharField(max_length=50)),
                ('transactionType', models.CharField(default='Purchased', max_length=15)),
                ('transactionDate', models.DateField()),
                ('totalPrice', models.FloatField(default=0.0)),
                ('discount', models.FloatField(default=0.0)),
                ('amountTopay', models.FloatField(default=0.0)),
                ('amountPaid', models.FloatField(default=0.0)),
                ('amountOwe', models.FloatField(default=0.0)),
                ('oweBalance', models.FloatField(default=0.0)),
                ('narration', models.CharField(max_length=500)),
                ('customerRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.retailandwholesalecustomers')),
                ('transactionBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref')),
            ],
        ),
    ]
