# Generated by Django 5.2.7 on 2026-01-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0005_allcustomertransactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecords',
            name='customerOwingBalance',
        ),
        migrations.RemoveField(
            model_name='salesrecords',
            name='transactionType',
        ),
    ]
