# Generated by Django 5.2.7 on 2026-01-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0006_remove_salesrecords_customerowingbalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcustomertransactions',
            name='paymentTerms',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
