# Generated by Django 5.2.7 on 2026-01-07 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0007_allcustomertransactions_paymentterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentagreement',
            name='customerRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salesApp.retailandwholesalecustomers'),
        ),
    ]
