# Generated by Django 5.2.7 on 2026-01-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0001_initial'),
        ('salesApp', '0009_remove_paymentagreement_customerref_and_more'),
        ('usersApp', '0001_initial'),
        ('warehouseApp', '0002_product_branhref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyquantityrecords',
            name='retailAndWholesaleRef',
        ),
        migrations.AddField(
            model_name='supplyquantityrecords',
            name='branchRef',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplyquantityrecords',
            name='productRef',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplyquantityrecords',
            name='receivedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref'),
            preserve_default=False,
        ),
    ]
