# Generated by Django 5.2.7 on 2026-01-08 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0010_remove_supplyquantityrecords_retailandwholesaleref_and_more'),
        ('warehouseApp', '0002_product_branhref'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyquantityrecords',
            name='Balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplyquantityrecords',
            name='amountPaid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplyquantityrecords',
            name='transactionType',
            field=models.CharField(default='Supply', max_length=15),
        ),
        migrations.AlterField(
            model_name='supplyquantityrecords',
            name='productRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.product'),
        ),
    ]
