# Generated by Django 5.2.7 on 2026-01-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0011_supplyquantityrecords_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyquantityrecords',
            name='receiptNumber',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
