# Generated by Django 5.2.7 on 2026-01-09 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0012_supplyquantityrecords_receiptnumber'),
        ('warehouseApp', '0002_product_branhref'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualItemsSupplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('unityCost', models.FloatField(default=0.0)),
                ('totalCost', models.FloatField(default=0.0)),
                ('productRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.product')),
                ('supplyRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.supplyquantityrecords')),
            ],
        ),
    ]
