# Generated by Django 5.2.7 on 2026-01-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0013_individualitemssupplied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyquantityrecords',
            name='productRef',
        ),
    ]
