# Generated by Django 5.2.7 on 2026-01-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0014_remove_supplyquantityrecords_productref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyquantityrecords',
            name='transactionID',
        ),
    ]
