# Generated by Django 5.2.7 on 2026-01-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0015_remove_supplyquantityrecords_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyquantityrecords',
            name='narration',
            field=models.CharField(default='', max_length=500),
        ),
    ]
