# Generated by Django 5.2.7 on 2026-01-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0016_supplyquantityrecords_narration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyquantityrecords',
            name='quantitySupplied',
        ),
    ]
