# Generated by Django 5.2.7 on 2026-01-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0017_remove_supplyquantityrecords_quantitysupplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyquantityrecords',
            name='isConfirm',
            field=models.BooleanField(default=False),
        ),
    ]
