# Generated by Django 5.2.7 on 2026-01-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0018_supplyquantityrecords_isconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyquantityrecords',
            name='amountOwe',
            field=models.FloatField(default=0.0),
        ),
    ]
