# Generated by Django 5.2.7 on 2026-01-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0019_supplyquantityrecords_amountowe'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyquantityrecords',
            name='transactionID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
