# Generated by Django 5.2.7 on 2026-01-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0020_supplyquantityrecords_transactionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplyquantityrecords',
            old_name='isConfirm',
            new_name='isDisabled',
        ),
    ]
