# Generated by Django 5.2.7 on 2026-01-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0021_rename_isconfirm_supplyquantityrecords_isdisabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritemspurchased',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
