# Generated by Django 5.2.7 on 2026-01-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0022_customeritemspurchased_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritemspurchased',
            name='costPerUnit',
            field=models.FloatField(default=0.0),
        ),
    ]
