# Generated by Django 5.2.7 on 2026-01-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0023_customeritemspurchased_costperunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailandwholesale',
            name='returnPeriod',
            field=models.IntegerField(default=0),
        ),
    ]
