# Generated by Django 5.2.7 on 2026-01-26 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0024_retailandwholesale_returnperiod'),
        ('usersApp', '0001_initial'),
        ('warehouseApp', '0002_product_branhref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnAmountToCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountToPay', models.FloatField(default=0.0)),
                ('salesRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.salesrecords')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnedProductsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('pricePerUnit', models.FloatField(default=0.0)),
                ('totalPrice', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('reason', models.CharField(max_length=300)),
                ('productRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.product')),
                ('returnedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref')),
                ('salesRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.salesrecords')),
            ],
        ),
    ]
