# Generated by Django 5.2.7 on 2026-01-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0025_returnamounttocustomer_returnedproductsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecords',
            name='amountReturned',
            field=models.FloatField(default=0.0),
        ),
    ]
