# Generated by Django 5.2.7 on 2026-02-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0026_salesrecords_amountreturned'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcustomertransactions',
            name='currentPayment',
            field=models.FloatField(default=0.0),
        ),
    ]
