# Generated by Django 5.2.7 on 2026-02-25 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0008_business_description'),
        ('salesApp', '0027_allcustomertransactions_currentpayment'),
        ('usersApp', '0001_initial'),
        ('warehouseApp', '0005_alter_product_belongstomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempSupplyQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.FloatField(default=0)),
                ('amountPaid', models.FloatField(default=0.0)),
                ('amountOwe', models.FloatField(default=0.0)),
                ('unityCost', models.FloatField(default=0.0)),
                ('totalCost', models.FloatField(default=0.0)),
                ('branchRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
                ('productRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.product')),
                ('userRef', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref')),
            ],
        ),
    ]
