# Generated by Django 5.2.7 on 2026-02-25 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0028_tempsupplyquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempsupplyquantity',
            name='supplierRef',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salesApp.productsuppliers'),
            preserve_default=False,
        ),
    ]
