# Generated by Django 5.2.7 on 2026-02-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0029_tempsupplyquantity_supplierref'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritemspurchased',
            name='unitDiscount',
            field=models.FloatField(default=0.0),
        ),
    ]
