# Generated by Django 5.2.7 on 2026-03-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0030_customeritemspurchased_unitdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritemspurchased',
            name='quantityReturned',
            field=models.FloatField(default=0),
        ),
    ]
