# Generated by Django 5.2.7 on 2026-03-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0031_customeritemspurchased_quantityreturned'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnamounttocustomer',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
