# Generated by Django 5.2.7 on 2026-03-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0032_returnamounttocustomer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailandwholesale',
            name='enableOnlineOrder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailandwholesale',
            name='minimumOrder',
            field=models.FloatField(default=1),
        ),
    ]
