# Generated by Django 5.2.7 on 2026-03-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0033_retailandwholesale_enableonlineorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailwholesalestally',
            name='transactionType',
            field=models.CharField(default='In', max_length=5),
        ),
    ]
