# Generated by Django 5.2.7 on 2026-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0034_alter_retailwholesalestally_transactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='transactionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='advancepaymentitemsdetails',
            name='operationType',
            field=models.CharField(default='Collected', max_length=50),
        ),
        migrations.AlterField(
            model_name='advancepaymentitemsdetails',
            name='receiverName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='advancepaymentitemsdetails',
            name='receiverTel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agreementconfirmationcode',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agreementconfirmationcode',
            name='transactionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='allcustomertransactions',
            name='paymentTerms',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='allcustomertransactions',
            name='transactionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='allcustomertransactions',
            name='transactionType',
            field=models.CharField(default='Purchased', max_length=50),
        ),
        migrations.AlterField(
            model_name='customeritemspurchased',
            name='measureUnit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customeritemspurchased',
            name='productCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customeritemspurchased',
            name='productName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customeritemspurchased',
            name='transactionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerowingdetails',
            name='operationType',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customerowingdetails',
            name='transactionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerpayments',
            name='paidBy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerpayments',
            name='transactionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='custommeasuringunit',
            name='unit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='custommeasuringunit',
            name='unityType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datesforpayments',
            name='day',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='excludedays',
            name='days',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='excludedays',
            name='transactionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='measuringunits',
            name='soldUnit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='measuringunits',
            name='stockedUnit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentagreement',
            name='paymentTerm',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentagreement',
            name='transactionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retailwholesalestally',
            name='transactionType',
            field=models.CharField(default='In', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnamounttocustomer',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='returnedproductsrecord',
            name='reason',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='customerName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='customerTel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='paymentTerms',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesrecords',
            name='transactionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustmentType',
            field=models.CharField(default='Wrong Entry', max_length=50),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='narration',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='transactionType',
            field=models.CharField(default='Out', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplyquantityrecords',
            name='transactionID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplyquantityrecords',
            name='transactionType',
            field=models.CharField(default='Supply', max_length=50),
        ),
        migrations.AlterField(
            model_name='temporalpurchasedetails',
            name='transactionID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transactionids',
            name='transactionID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
