# Generated by Django 5.2.7 on 2026-03-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessApp', '0002_initial'),
        ('eventManagementApp', '0001_initial'),
        ('farmApp', '0001_initial'),
        ('hotelApp', '0001_initial'),
        ('imageApp', '0001_initial'),
        ('manufacturingApp', '0001_initial'),
        ('realEstateApp', '0001_initial'),
        ('restaurantAndBarApp', '0001_initial'),
        ('salesApp', '0001_initial'),
        ('transportationApp', '0001_initial'),
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productIsDisabled', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('branchRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
                ('operationBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.FloatField(default=0.0)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref')),
                ('busRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productCode', models.CharField(max_length=50)),
                ('productDescription', models.CharField(max_length=500, null=True)),
                ('productCategory', models.CharField(max_length=100)),
                ('belongsToModel', models.CharField(default='Retail & Wholesale Business', max_length=100)),
                ('measureUnit', models.CharField(max_length=50)),
                ('discountRate', models.FloatField(default=0.0)),
                ('dateAdded', models.DateField()),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usersApp.userref')),
                ('branhRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
                ('busRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.business')),
                ('disbleRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouseApp.disabledproducts')),
                ('eventManagementRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eventManagementApp.eventmanagement')),
                ('farmRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='farmApp.farm')),
                ('hotelRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotelApp.hotel')),
                ('manufacturingRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manufacturingApp.manufacturing')),
                ('productImageRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imageApp.images')),
                ('realEstateRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='realEstateApp.realestate')),
                ('restaurantAndBarRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurantAndBarApp.restaurantandbar')),
                ('retailAndWholesaleRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='salesApp.retailandwholesale')),
                ('transportationRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transportationApp.transportation')),
            ],
        ),
    ]
