# Generated by Django 5.2.7 on 2026-01-07 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0001_initial'),
        ('warehouseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='branhRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch'),
        ),
    ]
