# Generated by Django 5.2.7 on 2026-02-02 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApp', '0001_initial'),
        ('warehouseApp', '0002_product_branhref'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImageRef',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imageApp.images'),
        ),
    ]
