# Generated by Django 5.2.7 on 2026-02-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseApp', '0003_product_productimageref'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='belongsToModel',
            field=models.CharField(default='RetailAndWholesale', max_length=30),
        ),
    ]
