# Generated by Django 5.2.7 on 2026-02-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseApp', '0004_product_belongstomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='belongsToModel',
            field=models.CharField(default='Retail & Wholesale Business', max_length=50),
        ),
    ]
