# Generated by Django 5.2.7 on 2026-03-06 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0008_business_description'),
        ('warehouseApp', '0005_alter_product_belongstomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerTel', models.CharField(max_length=30)),
                ('unitPrice', models.FloatField()),
                ('totalPrice', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('orderID', models.CharField(max_length=6)),
                ('date', models.DateTimeField()),
                ('branhRef', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='businessApp.businessbranch')),
                ('productRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouseApp.product')),
            ],
        ),
    ]
