# Generated by Django 5.2.7 on 2026-03-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseApp', '0006_customeraddtocart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerAddToCart',
        ),
    ]
