# Generated by Django 5.2.7 on 2026-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouseApp', '0007_delete_customeraddtocart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='belongsToModel',
            field=models.CharField(default='Retail & Wholesale Business', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='measureUnit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='productCategory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
