
busAccess = {
    '100':['Add User', 'You can add new user', '1'],
    '101':['Edit User', 'You can edit information of a user', '1'],
    '102':['Grant or Revoke Role', 'You can give a particular role access to a user or take that access from the user', '1'],
    '103':['Change branch', 'You can change the current branch of the user', '1'],
    '104':['Enable or Disable user', 'After user is disable, the user cannot log in into the system until he/she is enabled', '1'],
    '105':['Grant Administrators Access', 'You can grant a user an administrators access level this will allow him/her to access all modules', '1'],
    '106':['Change users status', 'You can change the status of a user by enabling or disabling the user. Disabled user cannot access the system at all.', '1'],

    '200':['Edit Business', 'You can edit information of the business', '2'],
    '201':['Add branch', 'You can add branch to the business', '2'],
    '202':['Edit branch', 'You can edit branch information', '2'],
    '203':['Set Operational time', 'You can set the opening and closing time of a branch', '2'],   
    '205':['Online visibility', 'You can set whether the  branch can be seen by the public or not', '2'],
    '206':['Switch Branch', 'This will allow the user to switch between branches', '2'],
    '207':['Printer Settings', 'Assign pinter to a particular user account', '2'],

    '300':['Add Product', 'This will allow user to add new product', '3'],
    '301':['Add Stock', 'This will allow user to add stock to a product', '3'],
    '303':['Change Price', 'This will allow the user change the price of a product', '3'],
    '307':['Disable Products', 'This will allow the user stop a particular product from selling', '3'],
    '308':['General Discount', 'This will allow the user give discount on prices of all products', '3'],
    '309':['Individual Product Discount', 'This will allow the user to set discount on the prices of individual products', '3'],
    '311':['Stock Adjustment', 'This will allow the user to adjust the stock of individual products', '3'],
    '312':['Set Restock Level', 'This will allow the user to set the restock level. The level at which a product should be alerted for restock', '3'],
    '313':['Change product image', 'This will allow the user to set or change the product image', '3'],
    '314':['Set Measuring Unit', 'This will allow the user to set measuring unit for products', '3'],    
    '315':['Online visibility', 'You can set whether a product can be seen by the public or not', '3'],
    '316':['Return Period', 'A period a customer can return a product', '3'],

    '400':['Branch Account Shortages', 'This will allow the user to access branch account cash shoratges', '4'],
    '401':['Branch Account Overages', 'This will allow the user to access branch account cash Overages', '4'],
    '402':['Branch Account Fund Transfer', 'This will allow the user to transfer fund from branch account', '4'],
    '403':['Branch Account Fund Deposit and Withdrawal', 'This will allow the user to deposit or withdraw funds from branch account', '4'],
    '404':['Branch Account Fund Transfer Authorization', 'This will allow the user to authorize fund transfer of a branch account', '4'],

    '500':['Business Account Fund Transfer', 'This will allow the user to transfer fund from business account', '5'],
    '501':['Business Account Fund Deposit and Withdrawal', 'This will allow the user to deposit or withdraw funds from business account', '5'],
    '502':['Business Account Fund Transfer Authorization', 'This will allow the user to authorize fund transfer of the business account', '5'],

    '1':['User Management', 'This will allow the user have access to user management page', '1'],
    '2':['Branch Management', 'This will allow the user have access to branch management page', '2'],
    '3':['Warehouse Management', 'This will allow to have access to warehouse management page', '3'],
    '4':['Branch Account Management', 'This will allow the user to have access to branch account management page', '4'],
    '5':['Business Account Management', 'This will allow the user to have access to business account management page', '5'],    
    
    # other accesss 
    '6':['Sell Products', 'This will allow the user check the account details of a particular user(Seller)', '6'],
    '7':['Cash Analysis', 'This will allow the user do cash analysis after selling', '6'],
    '8':['Performance Analysis', 'This will allow the user analyze the performance of a branch and entire business', '6'],
    '9':['Income Statement', 'This will allow the user to have access to branch or business income statement', '6'],
    '10':['Sales Records', 'This will allow the user to see all sales records', '6'],
    '11':['Customer Records', 'This will allow the user to see all customer records', '6'],
    '12':['Supplier Records', 'This will allow the user to see all supplier records', '6'],
    '13':['Operational Expenses', 'This will allow the user have access to expenses page', '6'],
    '14':['Awaiting Collection', 'This will allow the user have access to items awaiting collection page', '6'],
    '15':['Repayments', 'This will allow the user have access to repayments page', '6'],
    }