
busAccess = {
    '100':['Add User', 'You can add new user', '1'],
    '101':['Edit User', 'You can edit information of a user', '1'],
    '102':['Grant or Revoke Role', 'You can give a particular role access to a user or take that access from the user', '1'],
    '103':['Change branch', 'You can change the current branch of the user', '1'],
    '104':['Enable or Disable user', 'After user is disable, the user cannot log in into the system until he/she is enabled', '1'],
    
    '200':['Edit Business', 'You can edit information of the business', '2'],
    '201':['Add branch', 'You can add branch to the business', '2'],
    '202':['Edit branch', 'You can edit branch information', '2'],
    '203':['Set Operation time', 'You can set the opening and closing time of a branch', '2'],
    '204':['Set branch type', 'You can set the type of business for a particular branch', '2'],
    '205':['Online visibility', 'You can set whether the operation of a branch can be seen by the public or not', '2'],
    '206':['Branch Performance', 'This will allow you to see the performance of a particular branch', '2'],
    '207':['Branch Sales', 'You can see the sales of a branch', '2'],

    '300':['Create or Delete Product', 'This will allow user to add new product or remove a product', '3'],
    '301':['Add or Remove Quantity', 'This will allow user to add quantity to a product or remove quantity from the product', '3'],
    '302':['Edit Product', 'This will allow the user to edit information about a product', '3'],
    '303':['Change Price', 'This will allow the user change the price of a product', '3'],
    '304':['Sell Product', 'This will allow the user sell the product to a customer', '3'],
    '305':['Product Performance', 'This will allow the user see the perfomance of a particular product', '3'],
    '306':['Product Sales', 'This will allow the user see the sales of a product', '3'],
    '307':['Freeze Product', 'This will allow the user stop a particular product from selling', '3'],
    '308':['Sales Promotion', 'This will allow the user do promotions on a particular product', '3'],

    '400':['Business Account', 'This will allow the user check the account details of the business', '4'],
    '401':['Branch Account', 'This will allow the user check the account details of a branch', '4'],
    '402':['Selling Access', 'This will allow the user check the account details of a particular user(Seller)', '4'],
    '403':['Cash Analysis', 'This will allow the user do cash analysis after selling', '4'],
    '404':['Performance Analysis', 'This will allow the user analyze the performance of a branch and entire business', '4'],
    '405':['Income Statement', 'This will allow the user to have access to branch or business income statement', '4'],
    '406':['Sales Records', 'This will allow the user to see all sales records', '4'],
    '407':['Customer Records', 'This will allow the user to see all customer records', '4'],
    '408':['Supplier Records', 'This will allow the user to see all supplier records', '4'],
    '409':['Warehouse', 'This will allow to have access to warehouse page', '4'],
    '410':['Operational Expenses', 'This will allow the user have access to expenses page', '4'],
    '411':['User Management', 'This will allow the user have access to user management page', '4'],
    }